import {
  CertificateIcon,
  DoctorsBagWeakIcon,
  ElectronicsIcon,
  InsulinPenIcon,
  InsulinPenWeakIcon,
  RubberStampIcon,
  RulerVerticalIcon,
} from '../icons';
import {UsefLogo1Image, UsefLogo2Image} from '../images';

export default [
  {
    title: 'USEF membership',
    image: UsefLogo1Image,
    status: 'Current',
    details: 'Active',
    expDate: '2023-11-28',
    selected: true,
  },
  {
    title: 'FEI Registration',
    image: UsefLogo2Image,
    status: 'Registered',
    details: 'Active',
    expDate: '2023-11-28',
    selected: true,
  },
  {
    title: 'Coggins',
    image: CertificateIcon,
    status: 'Current',
    details: 'Active',
    expDate: '2023-11-28',
    selected: true,
  },
  {
    title: 'Microchip Status',
    image: ElectronicsIcon,
    status: 'Ineligible',
    details: 'Suspension ends',
    expDate: 'N...',
    selected: false,
  },
  {
    title: 'Age Verification',
    image: RubberStampIcon,
    status: 'True',
    details: 'Age has been verified b...',
    expDate: '2023-11-28',
    selected: true,
  },
  {
    title: 'Measurement Card',
    image: RulerVerticalIcon,
    status: 'Current',
    details: 'Active',
    expDate: '2023-11-28',
    selected: true,
  },
  {
    title: 'Health Certificate',
    image: DoctorsBagWeakIcon,
    status: 'Current',
    details: 'Active',
    expDate: '2023-11-28',
    selected: true,
  },
  {
    title: 'Vaccinations',
    image: InsulinPenWeakIcon,
    status: 'No record on file with USEF',
    details: '',
    expDate: '',
    selected: true,
  },
  {
    title: 'Rhinopneumonitis',
    image: InsulinPenWeakIcon,
    status: 'No record on file with USEF',
    details: '',
    expDate: '',
    selected: true,
  },
  {
    title: 'Influenza',
    image: InsulinPenIcon,
    status: 'Current',
    details: 'Active',
    expDate: '2023-11-28',
    selected: true,
  },
];
