import {
  UsefLogo1Image,
  UsefLogo2Image,
  UsefLogo3Image,
  UsefLogo4Image,
  UsefLogo5Image,
  UsefLogo6Image,
  UsefLogo7Image,
  UsefLogo8Image,
  UsefLogo9Image,
} from '../images';

export default [
  {
    title: 'USDF membership',
    image: UsefLogo1Image,
    status: 'Current',
    details: 'Active',
    expDate: 'November 31st, 2023',
    selected: true,
  },
  {
    title: 'USEA membership',
    image: UsefLogo2Image,
    status: 'N/A',
    details: 'No record on file with USEF',
    expDate: 'N/A',
    selected: false,
  },
  {
    title: 'USHJA membership',
    image: UsefLogo3Image,
    status: 'N/A',
    details: 'No record on file with USEF',
    expDate: 'N/A',
    selected: false,
  },

  {
    title: 'AHHS membership',
    image: UsefLogo5Image,
    status: 'N/A',
    details: 'No record on file with USEF',
    expDate: 'N/A',
    selected: false,
  },
  {
    title: 'AMHA membership',
    image: UsefLogo6Image,
    status: 'N/A',
    details: 'No record on file with USEF',
    expDate: 'N/A',
    selected: false,
  },
  {
    title: 'ARHPA membership',
    image: UsefLogo7Image,
    status: 'N/A',
    details: 'No record on file with USEF',
    expDate: 'N/A',
    selected: false,
  },
  {
    title: 'ASHA membership',
    image: UsefLogo8Image,
    status: 'N/A',
    details: 'No record on file with USEF',
    expDate: 'N/A',
    selected: false,
  },
  {
    title: 'UPHA membership',
    image: UsefLogo4Image,
    status: 'N/A',
    details: 'No record on file with USEF',
    expDate: 'N/A',
    selected: false,
  },
  {
    title: 'WDAA membership',
    image: UsefLogo9Image,
    status: 'N/A',
    details: 'No record on file with USEF',
    expDate: 'N/A',
    selected: false,
  },
];
