import {
  CalendarIcon,
  ExpensivePriceIcon,
  FarmIcon,
  MoneyBagIcon,
  ParliamentIcon,
  PrizeIcon,
  TransactionIcon,
  UserRegisterIcon,
} from '../icons';

export default [
  {
    icon: FarmIcon,
    title: 'Stalls',
    itemTitle1: 'Temporary',
    itemValue1: '30 available, $600 daily',
    itemTitle2: 'Permanent ',
    itemValue2: '0 available',
    itemTitle3: 'Private ',
    itemValue3: '10 available, $2000 weekly',
    itemTitle4: 'Circuit ',
    itemValue4: '0 available',
  },
  {
    icon: ParliamentIcon,
    title: 'Governance',
    itemTitle1: 'USEF fee',
    itemValue1: '$8',
    itemTitle2: 'USEF drug fee ',
    itemValue2: '$15',
    itemTitle3: 'USEF show pass ',
    itemValue3: '$45',
    itemTitle4: 'USHJA horse fee ',
    itemValue4: '$7',
  },
  {
    icon: TransactionIcon,
    title: 'Refunds',
    itemTitle1: 'Pre-close',
    itemValue1: '100%',
    itemTitle2: 'Post-close ',
    itemValue2: '50%',
    itemTitle3: 'Weather ',
    itemValue3: '0%',
    itemTitle4: 'Biosecurity ',
    itemValue4: '0%',
  },
  {
    icon: ExpensivePriceIcon,
    title: 'Other',
    itemTitle1: 'Paddock',
    itemValue1: '50 available, $20 daily',
    itemTitle2: 'RV Hookup ',
    itemValue2: '23 available, $50 daily',
    itemTitle3: 'Ship in / Ground fee ',
    itemValue3: 'N/A, $20 daily',
    itemTitle4: 'Internet Access ',
    itemValue4: 'N/A, $10 daily',
  },
];
