export default [
  {
    title: 'Stalls',
    fees: [
      {
        subTitle: 'Temporary stalls',
        available: '20',
        price: '200',
        rate: 'Daily',
        amount: 3,
        info: 'First come first served. No reserving s...More >',
      },
      {
        subTitle: 'Permanent stalls',
        available: '0',
        price: '200',
        rate: 'N/A',
        amount: null,
        info: 'We usually have permanenet stalls, ...More >',
      },
      {
        subTitle: 'Private stalls',
        available: '10',
        price: '2000',
        rate: 'Weekly',
        amount: null,
        info: 'Rubber matting, heated, close to rin...More >',
      },
      {
        subTitle: 'Circuit stalls',
        available: '0',
        price: 'N/A',
        rate: 'N/A',
        amount: null,
        info: 'First come first served. No reserving...More >',
      },
      {
        subTitle: 'Muck fee',
        available: '20',
        price: '50',
        rate: 'Daily',
        amount: null,
        info: 'N/A',
      },
    ],
  },
  {
    title: 'Bedding',
    fees: [
      {
        subTitle: 'Shavings',
        available: '200',
        price: '15',
        rate: 'Per bag',
        amount: 3,
        info: 'First come first served. No reserving s...More >',
      },
      {
        subTitle: 'Straw',
        available: '200',
        price: '20',
        rate: 'Per bag',
        amount: 3,
        info: 'First come first served. No reserving s...More >',
      },
    ],
  },
  {
    title: 'Feed',
    fees: [
      {
        subTitle: 'Coastal hay',
        available: '73',
        price: '15',
        rate: 'Per bale',
        amount: 3,
        info: 'First come first served. No reserving s...More >',
      },
      {
        subTitle: 'Timothy hay',
        available: '138',
        price: '20',
        rate: 'Per bale',
        amount: 3,
        info: 'First come first served. No reserving s...More >',
      },
      {
        subTitle: 'Alfalfa',
        available: '175',
        price: '20',
        rate: 'Per bale',
        amount: 3,
        info: 'First come first served. No reserving s...More >',
      },
      {
        subTitle: 'TnA',
        available: '200',
        price: '25',
        rate: 'Per bale',
        amount: 3,
        info: 'First come first served. No reserving s...More >',
      },
    ],
  },
  {
    title: 'Other fees',
    fees: [
      {
        subTitle: 'Temporary stalls',
        available: '20',
        price: '200',
        rate: 'Daily',
        amount: 1,
        info: 'First come first served. No reserving s...More >',
      },
      {
        subTitle: 'RV Hookup',
        available: '18',
        price: '200',
        rate: 'Daily',
        amount: null,
        info: 'First come first served. No reserving...More >',
      },
    ],
  },
];
