export default [
  {
    subTitle: 'General entry - Friday',
    available: '20',
    price: '200',
    amount: 3,
    info: 'First come first served. No reserving s...More >',
  },
  {
    subTitle: 'Permanent stalls',
    available: '0',
    price: '200',
    amount: null,
    info: 'We usually have permanenet stalls, ...More >',
  },
  {
    subTitle: 'Private stalls',
    available: '10',
    price: '2000',
    amount: null,
    info: 'Rubber matting, heated, close to rin...More >',
  },
  {
    subTitle: 'Circuit stalls',
    available: '0',
    price: 'N/A',
    amount: null,
    info: 'First come first served. No reserving...More >',
  },
  {
    subTitle: 'Muck fee',
    available: '20',
    price: '50',
    amount: null,
    info: 'N/A',
  },
  {
    subTitle: 'Shavings',
    available: '200',
    price: '15',
    amount: 3,
    info: 'First come first served. No reserving s...More >',
  },
  {
    subTitle: 'Straw',
    available: '200',
    price: '20',
    amount: 3,
    info: 'First come first served. No reserving s...More >',
  },
  {
    subTitle: 'Coastal hay',
    available: '73',
    price: '15',
    amount: 3,
    info: 'First come first served. No reserving s...More >',
  },
  {
    subTitle: 'Timothy hay',
    available: '138',
    price: '20',
    amount: 3,
    info: 'First come first served. No reserving s...More >',
  },
  {
    subTitle: 'Alfalfa',
    available: '175',
    price: '20',
    amount: 3,
    info: 'First come first served. No reserving s...More >',
  },
  {
    subTitle: 'TnA',
    available: '200',
    price: '25',
    amount: 3,
    info: 'First come first served. No reserving s...More >',
  },
];
