import {YearOfHorseIcon, YearOfHorseOutlinedIcon} from '../icons';

export default [
  {
    text: 'All',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'American Saddlebred',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Andalusian/Lusitano',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Arabian',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Carriage Pleasure ',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Driving',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Combined Driving',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Connemara',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Cutting',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Dressage',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Endurance',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'English Pleasure',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Equitation',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Eventing',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Friesian',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Gymkhana',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Hackney',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Horsemanship',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Hunter',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Hunter Jumper',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Jumper',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Morgan',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'National Horse Show',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Para-equestrian',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Parade Horse',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Paso FinoPony Club',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Reining',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Roadster',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Rodeo',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Roping',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Saddle seat',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Shetland',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Team Penning',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Trail',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Vaulting',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Welsh Pony/Cob',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Western',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Western Dressage',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Western Pleasure',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Western/reining Seat',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Equitation',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Western Riding',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
  {
    text: 'Working Cow Horse',
    icon: YearOfHorseIcon,
    selected: false,
    selectedIcon: YearOfHorseOutlinedIcon,
  },
];
