export const RecentSearch = ['WEF', 'WEF Winter', 'Clinic', 'Boyd Ma...'];
export const SearchedResult = [
  'Alice woods clinic 22',
  'Rockinghorse Horse clinic ',
  'Pony Club Clinic Jan 22',
  'Clinic: USPC September 22',
  'Rockinghorse Horse clinic ',
  'Pony Club Clinic Jan 22',
  'Clinic: USPC September 22',
  'Alice woods clinic 22',
  'Rockinghorse Horse clinic ',
  'Pony Club Clinic Jan 22',
  'Clinic: USPC September 22',
  'Rockinghorse Horse clinic ',
  'Pony Club Clinic Jan 22',
  'Clinic: USPC September 22',
  'Alice woods clinic 22',
  'Rockinghorse Horse clinic ',
  'Pony Club Clinic Jan 22',
  'Clinic: USPC September 22',
  'Rockinghorse Horse clinic ',
  'Pony Club Clinic Jan 22',
  'Clinic: USPC September 22',
  'Alice woods clinic 22',
  'Rockinghorse Horse clinic ',
  'Pony Club Clinic Jan 22',
  'Clinic: USPC September 22',
  'Rockinghorse Horse clinic ',
  'Pony Club Clinic Jan 22',
  'Clinic: USPC September 22',
  'Alice woods clinic 22',
  'Rockinghorse Horse clinic ',
  'Pony Club Clinic Jan 22',
  'Clinic: USPC September 22',
  'Rockinghorse Horse clinic ',
  'Pony Club Clinic Jan 22',
  'Clinic: USPC September 22',
];
